version: "3"
services:
  app:
    build: .
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_USER}\
      MYSQL_DATABASE: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:3306"
