version: "3"
services:
  app:
    build: .
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    depends_on:
      - db
  db:
    image: mysql
    hostname: db
    environment:
      TZ: "America/Bogota"
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
